shared:
  annotations:
    screwdriver.cd/cpu: TURBO
    screwdriver.cd/ram: TURBO
  image: hseeberger/scala-sbt:8u222_1.3.5_2.13.1
  #environment:
    #Fetches history so Sonar can assign blame.
    #GIT_SHALLOW_CLONE: false

jobs:
  pull-request:
    requires: [ ~pr ]
    steps:
      - build: ./sbt clean dist

  main:
    requires: [ ~commit ]
    steps:
      - prepare: echo "prepare"
      - build: ./sbt clean dist
      - publish: echo "publish"